system:
  name: "AlgoSpace Trading System"
  version: "0.1.0"
  mode: "backtest"  # "live", "paper", or "backtest"
  environment: ${ENVIRONMENT:development}
  
# Timeframes for multi-timeframe analysis
timeframes:
  - 5   # 5-minute bars
  - 30  # 30-minute bars
  
# Trading symbols
symbols:
  - "ES"   # E-mini S&P 500
  - "NQ"   # E-mini NASDAQ-100
  
# Data configuration
data_handler:
  type: "backtest"  # "rithmic", "ib", "backtest"
  backtest_file: "data/historical/ES - 5 min.csv"
  replay_speed: 1.0  # 1.0 = real-time, 0 = as fast as possible
  config:
    lookback_days: 60
    cache_enabled: true
    cache_path: "./data/cache/"
    
# Lookback windows for agents
lookback_windows:
  N_30m: 100
  N_5m: 100
  N_regime: 100
    
# Indicators configuration
indicators:
  mlmi:
    enabled: true
    periods: [14, 21, 50]
    sensitivity: 0.7
  nwrqk:
    enabled: true
    threshold: 0.8
  fvg:
    enabled: true
    threshold: 0.001
    lookback_period: 10
    body_multiplier: 1.5
    max_age: 50
    mitigation:
      penetration_weight: 0.4
      speed_weight: 0.3
      volume_weight: 0.2
      age_weight: 0.1
      min_penetration: 0.5
      volume_lookback: 20
    gap_size:
      max_percentage: 0.05
      min_percentage: 0.001
  lvn:
    enabled: true
    volume_profile_days: 20
  mmd:
    enabled: true
    signature_degree: 3
    window_size: 20
    
# SynergyDetector configuration
synergy_detector:
  # Time and sequence parameters
  time_window_bars: 10         # Maximum bars between signals for valid synergy
  cooldown_bars: 5             # Bars to wait before next detection
  bar_duration_minutes: 5      # Duration of each bar in minutes
  required_signals: 3          # Number of signals required for complete synergy
  
  # Signal activation thresholds
  mlmi_threshold: 0.5          # Minimum MLMI signal strength (0.5 = 50% deviation from neutral)
  mlmi_neutral_line: 50        # MLMI neutral line value
  mlmi_scaling_factor: 50      # Scaling factor for MLMI threshold calculation
  mlmi_max_strength: 1.0       # Maximum signal strength cap
  
  nwrqk_threshold: 0.3         # Minimum NW-RQK slope magnitude for signal
  nwrqk_max_slope: 2.0         # Maximum reasonable slope for normalization
  nwrqk_max_strength: 1.0      # Maximum signal strength cap
  
  fvg_min_size: 0.001          # Minimum FVG gap size (0.1% of price)
  fvg_max_gap_pct: 0.01        # Maximum gap percentage for normalization (1%)
  fvg_max_strength: 1.0        # Maximum signal strength cap
  
  # Performance monitoring
  processing_time_warning_ms: 1.0  # Processing time threshold for warnings
  
  # Default fallback values for missing features
  defaults:
    current_price: 0.0
    volatility: 0.0
    volume_ratio: 1.0
    volume_momentum: 0.0
    mlmi_value: 50
    nwrqk_slope: 0.0
    nwrqk_value: 0.0

# Matrix Assemblers configuration
matrix_assemblers:
  30m:
    window_size: 48  # 24 hours of 30-minute bars
    warmup_period: 48
    features:
      - mlmi_value
      - mlmi_signal
      - nwrqk_value
      - nwrqk_slope
      - lvn_distance_points
      - lvn_nearest_strength
      - time_hour_sin
      - time_hour_cos
    feature_configs:
      mlmi_value:
        ema_alpha: 0.02
      nwrqk_slope:
        ema_alpha: 0.05
      lvn_distance_points:
        ema_alpha: 0.01
  5m:
    window_size: 60  # 5 hours of 5-minute bars
    warmup_period: 20
    features:
      - fvg_bullish_active
      - fvg_bearish_active
      - fvg_nearest_level
      - fvg_age
      - fvg_mitigation_signal
      - price_momentum_5
      - volume_ratio
      - fvg_gap_size_pct
      - fvg_mitigation_strength
    feature_configs:
      price_momentum_5:
        ema_alpha: 0.1
      volume_ratio:
        ema_alpha: 0.05
      fvg_gap_size_pct:
        ema_alpha: 0.1
      fvg_mitigation_strength:
        ema_alpha: 0.05
  regime:
    window_size: 96  # 48 hours of 30-minute bars
    warmup_period: 30
    features:
      - volatility_30
      - volume_profile_skew
      - price_acceleration
      - momentum_divergence
      - regime_strength
    feature_configs:
      volatility_30:
        ema_alpha: 0.05
      volume_profile_skew:
        ema_alpha: 0.02
      price_acceleration:
        ema_alpha: 0.1
    
# MARL Agents configuration
agents:
  agent_30m:
    enabled: true
    model_path: "./models/agent_30m.pth"
    action_space: ["long", "short", "neutral"]
  agent_5m:
    enabled: true
    model_path: "./models/agent_5m.pth"
    action_space: ["enter", "exit", "hold"]
  agent_regime:
    enabled: true
    model_path: "./models/agent_regime.pth"
    regimes: ["trending", "ranging", "volatile"]
  agent_risk:
    enabled: true
    model_path: "./models/agent_risk.pth"
    
# Risk Management
risk_management:
  max_position_size: ${MAX_POSITION_SIZE:100000}
  max_daily_loss: ${MAX_DAILY_LOSS:5000}
  max_drawdown_percent: ${MAX_DRAWDOWN_PERCENT:10}
  stop_loss_percent: 2.0
  position_sizing_method: "kelly"
  
# Execution configuration
execution:
  order_type: "limit"  # "market", "limit"
  slippage_ticks: 1
  commission_per_contract: 2.5
  
# Backtesting specific
backtesting:
  start_date: ${BACKTEST_START_DATE:"2022-01-01"}
  end_date: ${BACKTEST_END_DATE:"2023-12-31"}
  initial_capital: ${BACKTEST_INITIAL_CAPITAL:100000}
  
# Logging configuration
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  handlers:
    - console
    - file
    
# Performance monitoring
monitoring:
  prometheus_port: ${PROMETHEUS_PORT:9090}
  enable_profiling: false
  metrics_interval: 60  # seconds

# RDE (Regime Detection Engine) configuration
rde:
  input_dim: 155  # Number of MMD features
  d_model: 256    # Transformer internal dimension
  latent_dim: 8   # Regime vector dimension
  n_heads: 8      # Attention heads
  n_layers: 3     # Transformer layers
  dropout: 0.1    # Dropout probability
  device: cpu     # CPU for production stability
  sequence_length: 24  # Expected sequence length (12 hours)

# M-RMS (Multi-Agent Risk Management Subsystem) configuration
m_rms:
  synergy_dim: 30         # Synergy feature vector dimension
  account_dim: 10         # Account state vector dimension  
  device: cpu             # CPU for production stability
  point_value: 5.0        # MES point value
  max_position_size: 5    # Maximum contracts per trade
  hidden_dim: 128         # Value head hidden dimension
  position_agent_hidden: 128
  sl_agent_hidden: 64
  pt_agent_hidden: 64
  dropout_rate: 0.2

# Main MARL Core configuration
main_core:
  device: cpu  # CPU for production stability
  embedders:
    structure:
      output_dim: 64
      dropout: 0.2
    tactical:
      input_dim: 9
      hidden_dim: 64
      output_dim: 32
      dropout: 0.2
    regime:
      output_dim: 16
      hidden_dim: 32
    lvn:
      input_dim: 5
      output_dim: 8
      hidden_dim: 16
  shared_policy:
    hidden_dims: [256, 128, 64]
    dropout: 0.2
  mc_dropout:
    n_passes: 50
    confidence_threshold: 0.65
  decision_gate:
    hidden_dim: 64
    dropout: 0.1
  model_paths:
    structure_embedder: "./models/structure_embedder.pth"
    tactical_embedder: "./models/tactical_embedder.pth"
    regime_embedder: "./models/regime_embedder.pth"
    lvn_embedder: "./models/lvn_embedder.pth"
    shared_policy: "./models/shared_policy.pth"
    decision_gate: "./models/decision_gate.pth"

# Model paths
models:
  rde_path: "./models/hybrid_regime_engine.pth"
  mrms_path: "./models/m_rms_model.pth"
# Data configuration (REQUIRED)
data:
  tick_buffer_size: 1000
  bar_buffer_size: 100
  max_memory_mb: 2048
  cleanup_interval: 60
  backtest_file: "data/historical/ES - 5 min.csv"
  
  # Thread safety
  use_locks: true
  max_concurrent_operations: 10
  
  # Recovery settings
  enable_recovery: true
  recovery_timeout: 30
  max_recovery_attempts: 3
